IMPORT ML;
EXPORT dconnect4:= MODULE
    cTypeRecord := RECORD
        INTEGER field1;
        INTEGER field2;
        INTEGER field3;
        INTEGER field4;
        INTEGER field5;
        INTEGER field6;
        INTEGER field7;
        INTEGER field8;
        INTEGER field9;
        INTEGER field10;
        INTEGER field11;
        INTEGER field12;
        INTEGER field13;
        INTEGER field14;
        INTEGER field15;
        INTEGER field16;
        INTEGER field17;
        INTEGER field18;
        INTEGER field19;
        INTEGER field20;
        INTEGER field21;
        INTEGER field22;
        INTEGER field23;
        INTEGER field24;
        INTEGER field25;
        INTEGER field26;
        INTEGER field27;
        INTEGER field28;
        INTEGER field29;
        INTEGER field30;
        INTEGER field31;
        INTEGER field32;
        INTEGER field33;
        INTEGER field34;
        INTEGER field35;
        INTEGER field36;
        INTEGER field37;
        INTEGER field38;
        INTEGER field39;
        INTEGER field40;
        INTEGER field41;
        INTEGER field42;
        INTEGER class;
    END;

    ctype := RECORD
       INTEGER id;
       cTypeRecord;
    END;
    connect4DS:= DATASET('~vivek::pt::connect4.csv', cTypeRecord, CSV);
    SHARED DS:= PROJECT(connect4DS, TRANSFORM(cType, SELF.id:=COUNTER, SELF:= LEFT));
    SHARED number_of_records := COUNT(DS);
    EXPORT Training := DS(id < 0.4 * number_of_records);
    EXPORT Tuning := DS(0.4 * number_of_records <= id AND id <0.6 * number_of_records);
    EXPORT Testing := DS(0.6 * number_of_records < id);
END;